
// new Promise((resolve, reject) => {
//     resolve('成功！');
// })
//     .then(res => console.log(res))
//     .catch(err => console.log(err))
//     .finally(() => console.log('无论成功还是失败都会执行 finally '));